/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModQueueRouteImport } from './routes/mod-queue'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedActivityFeedRouteImport } from './routes/_authenticated/activity-feed'
import { Route as AuthenticatedClipCommandRouteImport } from './routes/_authenticated/clip-command'
import { Route as AuthenticatedClipsRouteImport } from './routes/_authenticated/clips'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGiveawayRouteImport } from './routes/_authenticated/giveaway'
import { Route as AuthenticatedLiveCounterRouteImport } from './routes/_authenticated/live-counter'
import { Route as AuthenticatedMediaRequestsRouteImport } from './routes/_authenticated/media-requests'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ClipIdRouteImport } from './routes/clip.$id'
import { Route as OverlayPublicIdRouteImport } from './routes/overlay.$publicId'
import { Route as OverlayGiveawayRouteImport } from './routes/overlay.giveaway'
import { Route as OverlayMediaRequestRouteImport } from './routes/overlay.media-request'
import { Route as OverlaySubathonTimerRouteImport } from './routes/overlay.subathon-timer'
import { Route as OverlayTiktokTapGoalRouteImport } from './routes/overlay.tiktok-tap-goal'
import { Route as OverlayTiktokTappersRouteImport } from './routes/overlay.tiktok-tappers'
import { Route as AuthenticatedWidgetsIndexRouteImport } from './routes/_authenticated/widgets.index'
import { Route as AuthenticatedWidgetsWidgetIdRouteImport } from './routes/_authenticated/widgets.$widgetId'
import { Route as AuthenticatedSubathonsIdControlRouteImport } from './routes/_authenticated/subathons.$id.control'
import { Route as AuthenticatedSubathonsIdOverlayRouteImport } from './routes/_authenticated/subathons.$id.overlay'
import { Route as AuthenticatedSubathonsIdRulesRouteImport } from './routes/_authenticated/subathons.$id.rules'
import { Route as AuthenticatedWidgetsWidgetIdIndexRouteImport } from './routes/_authenticated/widgets.$widgetId.index'
import { Route as AuthenticatedWidgetsWidgetIdControlRouteImport } from './routes/_authenticated/widgets.$widgetId.control'
import { Route as AuthenticatedWidgetsWidgetIdGoalRouteImport } from './routes/_authenticated/widgets.$widgetId.goal'
import { Route as AuthenticatedWidgetsWidgetIdRulesRouteImport } from './routes/_authenticated/widgets.$widgetId.rules'
import { Route as ApiAuthCallbackTiktokRouteImport } from './routes/api/auth/callback/tiktok'
import { Route as ApiPublicClipIdRouteImport } from './routes/api/public/clip/$id'
import { Route as ApiPublicWebhooksKickRouteImport } from './routes/api/public/webhooks/kick'
import { Route as ApiPublicWebhooksStreamelementsRouteImport } from './routes/api/public/webhooks/streamelements'
import { Route as ApiPublicWebhooksStreamlabsRouteImport } from './routes/api/public/webhooks/streamlabs'
import { Route as ApiPublicWebhooksTwitchRouteImport } from './routes/api/public/webhooks/twitch'
import { Route as ApiPublicAuthProviderCallbackRouteImport } from './routes/api/public/auth/$provider/callback'
import { Route as ApiPublicAuthProviderStartRouteImport } from './routes/api/public/auth/$provider/start'
import { Route as ApiPublicGiveawayTokenLiveRouteImport } from './routes/api/public/giveaway/$token/live'
import { Route as ApiPublicMediaRequestTokenAdvanceRouteImport } from './routes/api/public/media-request/$token/advance'
import { Route as ApiPublicMediaRequestTokenLiveRouteImport } from './routes/api/public/media-request/$token/live'
import { Route as ApiPublicMediaRequestTokenStreamRouteImport } from './routes/api/public/media-request/$token/stream'
import { Route as ApiPublicModQueueTokenActionRouteImport } from './routes/api/public/mod-queue/$token/action'
import { Route as ApiPublicModQueueTokenQueueRouteImport } from './routes/api/public/mod-queue/$token/queue'
import { Route as ApiPublicOverlayPublicIdLiveRouteImport } from './routes/api/public/overlay/$publicId/live'
import { Route as ApiPublicOverlayPublicIdMetaRouteImport } from './routes/api/public/overlay/$publicId/meta'
import { Route as ApiPublicOverlayPublicIdStreamRouteImport } from './routes/api/public/overlay/$publicId/stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModQueueRoute = ModQueueRouteImport.update({
  id: '/mod-queue',
  path: '/mod-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityFeedRoute =
  AuthenticatedActivityFeedRouteImport.update({
    id: '/activity-feed',
    path: '/activity-feed',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClipCommandRoute =
  AuthenticatedClipCommandRouteImport.update({
    id: '/clip-command',
    path: '/clip-command',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClipsRoute = AuthenticatedClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGiveawayRoute = AuthenticatedGiveawayRouteImport.update({
  id: '/giveaway',
  path: '/giveaway',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveCounterRoute =
  AuthenticatedLiveCounterRouteImport.update({
    id: '/live-counter',
    path: '/live-counter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMediaRequestsRoute =
  AuthenticatedMediaRequestsRouteImport.update({
    id: '/media-requests',
    path: '/media-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipIdRoute = ClipIdRouteImport.update({
  id: '/clip/$id',
  path: '/clip/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayPublicIdRoute = OverlayPublicIdRouteImport.update({
  id: '/overlay/$publicId',
  path: '/overlay/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayGiveawayRoute = OverlayGiveawayRouteImport.update({
  id: '/overlay/giveaway',
  path: '/overlay/giveaway',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayMediaRequestRoute = OverlayMediaRequestRouteImport.update({
  id: '/overlay/media-request',
  path: '/overlay/media-request',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlaySubathonTimerRoute = OverlaySubathonTimerRouteImport.update({
  id: '/overlay/subathon-timer',
  path: '/overlay/subathon-timer',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayTiktokTapGoalRoute = OverlayTiktokTapGoalRouteImport.update({
  id: '/overlay/tiktok-tap-goal',
  path: '/overlay/tiktok-tap-goal',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayTiktokTappersRoute = OverlayTiktokTappersRouteImport.update({
  id: '/overlay/tiktok-tappers',
  path: '/overlay/tiktok-tappers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWidgetsIndexRoute =
  AuthenticatedWidgetsIndexRouteImport.update({
    id: '/widgets/',
    path: '/widgets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWidgetsWidgetIdRoute =
  AuthenticatedWidgetsWidgetIdRouteImport.update({
    id: '/widgets/$widgetId',
    path: '/widgets/$widgetId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubathonsIdControlRoute =
  AuthenticatedSubathonsIdControlRouteImport.update({
    id: '/subathons/$id/control',
    path: '/subathons/$id/control',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubathonsIdOverlayRoute =
  AuthenticatedSubathonsIdOverlayRouteImport.update({
    id: '/subathons/$id/overlay',
    path: '/subathons/$id/overlay',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubathonsIdRulesRoute =
  AuthenticatedSubathonsIdRulesRouteImport.update({
    id: '/subathons/$id/rules',
    path: '/subathons/$id/rules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWidgetsWidgetIdIndexRoute =
  AuthenticatedWidgetsWidgetIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWidgetsWidgetIdRoute,
  } as any)
const AuthenticatedWidgetsWidgetIdControlRoute =
  AuthenticatedWidgetsWidgetIdControlRouteImport.update({
    id: '/control',
    path: '/control',
    getParentRoute: () => AuthenticatedWidgetsWidgetIdRoute,
  } as any)
const AuthenticatedWidgetsWidgetIdGoalRoute =
  AuthenticatedWidgetsWidgetIdGoalRouteImport.update({
    id: '/goal',
    path: '/goal',
    getParentRoute: () => AuthenticatedWidgetsWidgetIdRoute,
  } as any)
const AuthenticatedWidgetsWidgetIdRulesRoute =
  AuthenticatedWidgetsWidgetIdRulesRouteImport.update({
    id: '/rules',
    path: '/rules',
    getParentRoute: () => AuthenticatedWidgetsWidgetIdRoute,
  } as any)
const ApiAuthCallbackTiktokRoute = ApiAuthCallbackTiktokRouteImport.update({
  id: '/api/auth/callback/tiktok',
  path: '/api/auth/callback/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClipIdRoute = ApiPublicClipIdRouteImport.update({
  id: '/api/public/clip/$id',
  path: '/api/public/clip/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksKickRoute = ApiPublicWebhooksKickRouteImport.update({
  id: '/api/public/webhooks/kick',
  path: '/api/public/webhooks/kick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksStreamelementsRoute =
  ApiPublicWebhooksStreamelementsRouteImport.update({
    id: '/api/public/webhooks/streamelements',
    path: '/api/public/webhooks/streamelements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksStreamlabsRoute =
  ApiPublicWebhooksStreamlabsRouteImport.update({
    id: '/api/public/webhooks/streamlabs',
    path: '/api/public/webhooks/streamlabs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksTwitchRoute = ApiPublicWebhooksTwitchRouteImport.update({
  id: '/api/public/webhooks/twitch',
  path: '/api/public/webhooks/twitch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthProviderCallbackRoute =
  ApiPublicAuthProviderCallbackRouteImport.update({
    id: '/api/public/auth/$provider/callback',
    path: '/api/public/auth/$provider/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthProviderStartRoute =
  ApiPublicAuthProviderStartRouteImport.update({
    id: '/api/public/auth/$provider/start',
    path: '/api/public/auth/$provider/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGiveawayTokenLiveRoute =
  ApiPublicGiveawayTokenLiveRouteImport.update({
    id: '/api/public/giveaway/$token/live',
    path: '/api/public/giveaway/$token/live',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMediaRequestTokenAdvanceRoute =
  ApiPublicMediaRequestTokenAdvanceRouteImport.update({
    id: '/api/public/media-request/$token/advance',
    path: '/api/public/media-request/$token/advance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMediaRequestTokenLiveRoute =
  ApiPublicMediaRequestTokenLiveRouteImport.update({
    id: '/api/public/media-request/$token/live',
    path: '/api/public/media-request/$token/live',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMediaRequestTokenStreamRoute =
  ApiPublicMediaRequestTokenStreamRouteImport.update({
    id: '/api/public/media-request/$token/stream',
    path: '/api/public/media-request/$token/stream',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicModQueueTokenActionRoute =
  ApiPublicModQueueTokenActionRouteImport.update({
    id: '/api/public/mod-queue/$token/action',
    path: '/api/public/mod-queue/$token/action',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicModQueueTokenQueueRoute =
  ApiPublicModQueueTokenQueueRouteImport.update({
    id: '/api/public/mod-queue/$token/queue',
    path: '/api/public/mod-queue/$token/queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOverlayPublicIdLiveRoute =
  ApiPublicOverlayPublicIdLiveRouteImport.update({
    id: '/api/public/overlay/$publicId/live',
    path: '/api/public/overlay/$publicId/live',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOverlayPublicIdMetaRoute =
  ApiPublicOverlayPublicIdMetaRouteImport.update({
    id: '/api/public/overlay/$publicId/meta',
    path: '/api/public/overlay/$publicId/meta',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOverlayPublicIdStreamRoute =
  ApiPublicOverlayPublicIdStreamRouteImport.update({
    id: '/api/public/overlay/$publicId/stream',
    path: '/api/public/overlay/$publicId/stream',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mod-queue': typeof ModQueueRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/activity-feed': typeof AuthenticatedActivityFeedRoute
  '/clip-command': typeof AuthenticatedClipCommandRoute
  '/clips': typeof AuthenticatedClipsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/giveaway': typeof AuthenticatedGiveawayRoute
  '/live-counter': typeof AuthenticatedLiveCounterRoute
  '/media-requests': typeof AuthenticatedMediaRequestsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/clip/$id': typeof ClipIdRoute
  '/overlay/$publicId': typeof OverlayPublicIdRoute
  '/overlay/giveaway': typeof OverlayGiveawayRoute
  '/overlay/media-request': typeof OverlayMediaRequestRoute
  '/overlay/subathon-timer': typeof OverlaySubathonTimerRoute
  '/overlay/tiktok-tap-goal': typeof OverlayTiktokTapGoalRoute
  '/overlay/tiktok-tappers': typeof OverlayTiktokTappersRoute
  '/widgets/$widgetId': typeof AuthenticatedWidgetsWidgetIdRouteWithChildren
  '/widgets/': typeof AuthenticatedWidgetsIndexRoute
  '/subathons/$id/control': typeof AuthenticatedSubathonsIdControlRoute
  '/subathons/$id/overlay': typeof AuthenticatedSubathonsIdOverlayRoute
  '/subathons/$id/rules': typeof AuthenticatedSubathonsIdRulesRoute
  '/widgets/$widgetId/control': typeof AuthenticatedWidgetsWidgetIdControlRoute
  '/widgets/$widgetId/goal': typeof AuthenticatedWidgetsWidgetIdGoalRoute
  '/widgets/$widgetId/rules': typeof AuthenticatedWidgetsWidgetIdRulesRoute
  '/api/auth/callback/tiktok': typeof ApiAuthCallbackTiktokRoute
  '/api/public/clip/$id': typeof ApiPublicClipIdRoute
  '/api/public/webhooks/kick': typeof ApiPublicWebhooksKickRoute
  '/api/public/webhooks/streamelements': typeof ApiPublicWebhooksStreamelementsRoute
  '/api/public/webhooks/streamlabs': typeof ApiPublicWebhooksStreamlabsRoute
  '/api/public/webhooks/twitch': typeof ApiPublicWebhooksTwitchRoute
  '/widgets/$widgetId/': typeof AuthenticatedWidgetsWidgetIdIndexRoute
  '/api/public/auth/$provider/callback': typeof ApiPublicAuthProviderCallbackRoute
  '/api/public/auth/$provider/start': typeof ApiPublicAuthProviderStartRoute
  '/api/public/giveaway/$token/live': typeof ApiPublicGiveawayTokenLiveRoute
  '/api/public/media-request/$token/advance': typeof ApiPublicMediaRequestTokenAdvanceRoute
  '/api/public/media-request/$token/live': typeof ApiPublicMediaRequestTokenLiveRoute
  '/api/public/media-request/$token/stream': typeof ApiPublicMediaRequestTokenStreamRoute
  '/api/public/mod-queue/$token/action': typeof ApiPublicModQueueTokenActionRoute
  '/api/public/mod-queue/$token/queue': typeof ApiPublicModQueueTokenQueueRoute
  '/api/public/overlay/$publicId/live': typeof ApiPublicOverlayPublicIdLiveRoute
  '/api/public/overlay/$publicId/meta': typeof ApiPublicOverlayPublicIdMetaRoute
  '/api/public/overlay/$publicId/stream': typeof ApiPublicOverlayPublicIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mod-queue': typeof ModQueueRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/activity-feed': typeof AuthenticatedActivityFeedRoute
  '/clip-command': typeof AuthenticatedClipCommandRoute
  '/clips': typeof AuthenticatedClipsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/giveaway': typeof AuthenticatedGiveawayRoute
  '/live-counter': typeof AuthenticatedLiveCounterRoute
  '/media-requests': typeof AuthenticatedMediaRequestsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/clip/$id': typeof ClipIdRoute
  '/overlay/$publicId': typeof OverlayPublicIdRoute
  '/overlay/giveaway': typeof OverlayGiveawayRoute
  '/overlay/media-request': typeof OverlayMediaRequestRoute
  '/overlay/subathon-timer': typeof OverlaySubathonTimerRoute
  '/overlay/tiktok-tap-goal': typeof OverlayTiktokTapGoalRoute
  '/overlay/tiktok-tappers': typeof OverlayTiktokTappersRoute
  '/widgets': typeof AuthenticatedWidgetsIndexRoute
  '/subathons/$id/control': typeof AuthenticatedSubathonsIdControlRoute
  '/subathons/$id/overlay': typeof AuthenticatedSubathonsIdOverlayRoute
  '/subathons/$id/rules': typeof AuthenticatedSubathonsIdRulesRoute
  '/widgets/$widgetId/control': typeof AuthenticatedWidgetsWidgetIdControlRoute
  '/widgets/$widgetId/goal': typeof AuthenticatedWidgetsWidgetIdGoalRoute
  '/widgets/$widgetId/rules': typeof AuthenticatedWidgetsWidgetIdRulesRoute
  '/api/auth/callback/tiktok': typeof ApiAuthCallbackTiktokRoute
  '/api/public/clip/$id': typeof ApiPublicClipIdRoute
  '/api/public/webhooks/kick': typeof ApiPublicWebhooksKickRoute
  '/api/public/webhooks/streamelements': typeof ApiPublicWebhooksStreamelementsRoute
  '/api/public/webhooks/streamlabs': typeof ApiPublicWebhooksStreamlabsRoute
  '/api/public/webhooks/twitch': typeof ApiPublicWebhooksTwitchRoute
  '/widgets/$widgetId': typeof AuthenticatedWidgetsWidgetIdIndexRoute
  '/api/public/auth/$provider/callback': typeof ApiPublicAuthProviderCallbackRoute
  '/api/public/auth/$provider/start': typeof ApiPublicAuthProviderStartRoute
  '/api/public/giveaway/$token/live': typeof ApiPublicGiveawayTokenLiveRoute
  '/api/public/media-request/$token/advance': typeof ApiPublicMediaRequestTokenAdvanceRoute
  '/api/public/media-request/$token/live': typeof ApiPublicMediaRequestTokenLiveRoute
  '/api/public/media-request/$token/stream': typeof ApiPublicMediaRequestTokenStreamRoute
  '/api/public/mod-queue/$token/action': typeof ApiPublicModQueueTokenActionRoute
  '/api/public/mod-queue/$token/queue': typeof ApiPublicModQueueTokenQueueRoute
  '/api/public/overlay/$publicId/live': typeof ApiPublicOverlayPublicIdLiveRoute
  '/api/public/overlay/$publicId/meta': typeof ApiPublicOverlayPublicIdMetaRoute
  '/api/public/overlay/$publicId/stream': typeof ApiPublicOverlayPublicIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/mod-queue': typeof ModQueueRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/activity-feed': typeof AuthenticatedActivityFeedRoute
  '/_authenticated/clip-command': typeof AuthenticatedClipCommandRoute
  '/_authenticated/clips': typeof AuthenticatedClipsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/giveaway': typeof AuthenticatedGiveawayRoute
  '/_authenticated/live-counter': typeof AuthenticatedLiveCounterRoute
  '/_authenticated/media-requests': typeof AuthenticatedMediaRequestsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/clip/$id': typeof ClipIdRoute
  '/overlay/$publicId': typeof OverlayPublicIdRoute
  '/overlay/giveaway': typeof OverlayGiveawayRoute
  '/overlay/media-request': typeof OverlayMediaRequestRoute
  '/overlay/subathon-timer': typeof OverlaySubathonTimerRoute
  '/overlay/tiktok-tap-goal': typeof OverlayTiktokTapGoalRoute
  '/overlay/tiktok-tappers': typeof OverlayTiktokTappersRoute
  '/_authenticated/widgets/$widgetId': typeof AuthenticatedWidgetsWidgetIdRouteWithChildren
  '/_authenticated/widgets/': typeof AuthenticatedWidgetsIndexRoute
  '/_authenticated/subathons/$id/control': typeof AuthenticatedSubathonsIdControlRoute
  '/_authenticated/subathons/$id/overlay': typeof AuthenticatedSubathonsIdOverlayRoute
  '/_authenticated/subathons/$id/rules': typeof AuthenticatedSubathonsIdRulesRoute
  '/_authenticated/widgets/$widgetId/control': typeof AuthenticatedWidgetsWidgetIdControlRoute
  '/_authenticated/widgets/$widgetId/goal': typeof AuthenticatedWidgetsWidgetIdGoalRoute
  '/_authenticated/widgets/$widgetId/rules': typeof AuthenticatedWidgetsWidgetIdRulesRoute
  '/api/auth/callback/tiktok': typeof ApiAuthCallbackTiktokRoute
  '/api/public/clip/$id': typeof ApiPublicClipIdRoute
  '/api/public/webhooks/kick': typeof ApiPublicWebhooksKickRoute
  '/api/public/webhooks/streamelements': typeof ApiPublicWebhooksStreamelementsRoute
  '/api/public/webhooks/streamlabs': typeof ApiPublicWebhooksStreamlabsRoute
  '/api/public/webhooks/twitch': typeof ApiPublicWebhooksTwitchRoute
  '/_authenticated/widgets/$widgetId/': typeof AuthenticatedWidgetsWidgetIdIndexRoute
  '/api/public/auth/$provider/callback': typeof ApiPublicAuthProviderCallbackRoute
  '/api/public/auth/$provider/start': typeof ApiPublicAuthProviderStartRoute
  '/api/public/giveaway/$token/live': typeof ApiPublicGiveawayTokenLiveRoute
  '/api/public/media-request/$token/advance': typeof ApiPublicMediaRequestTokenAdvanceRoute
  '/api/public/media-request/$token/live': typeof ApiPublicMediaRequestTokenLiveRoute
  '/api/public/media-request/$token/stream': typeof ApiPublicMediaRequestTokenStreamRoute
  '/api/public/mod-queue/$token/action': typeof ApiPublicModQueueTokenActionRoute
  '/api/public/mod-queue/$token/queue': typeof ApiPublicModQueueTokenQueueRoute
  '/api/public/overlay/$publicId/live': typeof ApiPublicOverlayPublicIdLiveRoute
  '/api/public/overlay/$publicId/meta': typeof ApiPublicOverlayPublicIdMetaRoute
  '/api/public/overlay/$publicId/stream': typeof ApiPublicOverlayPublicIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mod-queue'
    | '/privacy'
    | '/terms'
    | '/activity-feed'
    | '/clip-command'
    | '/clips'
    | '/dashboard'
    | '/giveaway'
    | '/live-counter'
    | '/media-requests'
    | '/settings'
    | '/auth/callback'
    | '/clip/$id'
    | '/overlay/$publicId'
    | '/overlay/giveaway'
    | '/overlay/media-request'
    | '/overlay/subathon-timer'
    | '/overlay/tiktok-tap-goal'
    | '/overlay/tiktok-tappers'
    | '/widgets/$widgetId'
    | '/widgets/'
    | '/subathons/$id/control'
    | '/subathons/$id/overlay'
    | '/subathons/$id/rules'
    | '/widgets/$widgetId/control'
    | '/widgets/$widgetId/goal'
    | '/widgets/$widgetId/rules'
    | '/api/auth/callback/tiktok'
    | '/api/public/clip/$id'
    | '/api/public/webhooks/kick'
    | '/api/public/webhooks/streamelements'
    | '/api/public/webhooks/streamlabs'
    | '/api/public/webhooks/twitch'
    | '/widgets/$widgetId/'
    | '/api/public/auth/$provider/callback'
    | '/api/public/auth/$provider/start'
    | '/api/public/giveaway/$token/live'
    | '/api/public/media-request/$token/advance'
    | '/api/public/media-request/$token/live'
    | '/api/public/media-request/$token/stream'
    | '/api/public/mod-queue/$token/action'
    | '/api/public/mod-queue/$token/queue'
    | '/api/public/overlay/$publicId/live'
    | '/api/public/overlay/$publicId/meta'
    | '/api/public/overlay/$publicId/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mod-queue'
    | '/privacy'
    | '/terms'
    | '/activity-feed'
    | '/clip-command'
    | '/clips'
    | '/dashboard'
    | '/giveaway'
    | '/live-counter'
    | '/media-requests'
    | '/settings'
    | '/auth/callback'
    | '/clip/$id'
    | '/overlay/$publicId'
    | '/overlay/giveaway'
    | '/overlay/media-request'
    | '/overlay/subathon-timer'
    | '/overlay/tiktok-tap-goal'
    | '/overlay/tiktok-tappers'
    | '/widgets'
    | '/subathons/$id/control'
    | '/subathons/$id/overlay'
    | '/subathons/$id/rules'
    | '/widgets/$widgetId/control'
    | '/widgets/$widgetId/goal'
    | '/widgets/$widgetId/rules'
    | '/api/auth/callback/tiktok'
    | '/api/public/clip/$id'
    | '/api/public/webhooks/kick'
    | '/api/public/webhooks/streamelements'
    | '/api/public/webhooks/streamlabs'
    | '/api/public/webhooks/twitch'
    | '/widgets/$widgetId'
    | '/api/public/auth/$provider/callback'
    | '/api/public/auth/$provider/start'
    | '/api/public/giveaway/$token/live'
    | '/api/public/media-request/$token/advance'
    | '/api/public/media-request/$token/live'
    | '/api/public/media-request/$token/stream'
    | '/api/public/mod-queue/$token/action'
    | '/api/public/mod-queue/$token/queue'
    | '/api/public/overlay/$publicId/live'
    | '/api/public/overlay/$publicId/meta'
    | '/api/public/overlay/$publicId/stream'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/mod-queue'
    | '/privacy'
    | '/terms'
    | '/_authenticated/activity-feed'
    | '/_authenticated/clip-command'
    | '/_authenticated/clips'
    | '/_authenticated/dashboard'
    | '/_authenticated/giveaway'
    | '/_authenticated/live-counter'
    | '/_authenticated/media-requests'
    | '/_authenticated/settings'
    | '/auth/callback'
    | '/clip/$id'
    | '/overlay/$publicId'
    | '/overlay/giveaway'
    | '/overlay/media-request'
    | '/overlay/subathon-timer'
    | '/overlay/tiktok-tap-goal'
    | '/overlay/tiktok-tappers'
    | '/_authenticated/widgets/$widgetId'
    | '/_authenticated/widgets/'
    | '/_authenticated/subathons/$id/control'
    | '/_authenticated/subathons/$id/overlay'
    | '/_authenticated/subathons/$id/rules'
    | '/_authenticated/widgets/$widgetId/control'
    | '/_authenticated/widgets/$widgetId/goal'
    | '/_authenticated/widgets/$widgetId/rules'
    | '/api/auth/callback/tiktok'
    | '/api/public/clip/$id'
    | '/api/public/webhooks/kick'
    | '/api/public/webhooks/streamelements'
    | '/api/public/webhooks/streamlabs'
    | '/api/public/webhooks/twitch'
    | '/_authenticated/widgets/$widgetId/'
    | '/api/public/auth/$provider/callback'
    | '/api/public/auth/$provider/start'
    | '/api/public/giveaway/$token/live'
    | '/api/public/media-request/$token/advance'
    | '/api/public/media-request/$token/live'
    | '/api/public/media-request/$token/stream'
    | '/api/public/mod-queue/$token/action'
    | '/api/public/mod-queue/$token/queue'
    | '/api/public/overlay/$publicId/live'
    | '/api/public/overlay/$publicId/meta'
    | '/api/public/overlay/$publicId/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ModQueueRoute: typeof ModQueueRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ClipIdRoute: typeof ClipIdRoute
  OverlayPublicIdRoute: typeof OverlayPublicIdRoute
  OverlayGiveawayRoute: typeof OverlayGiveawayRoute
  OverlayMediaRequestRoute: typeof OverlayMediaRequestRoute
  OverlaySubathonTimerRoute: typeof OverlaySubathonTimerRoute
  OverlayTiktokTapGoalRoute: typeof OverlayTiktokTapGoalRoute
  OverlayTiktokTappersRoute: typeof OverlayTiktokTappersRoute
  ApiAuthCallbackTiktokRoute: typeof ApiAuthCallbackTiktokRoute
  ApiPublicClipIdRoute: typeof ApiPublicClipIdRoute
  ApiPublicWebhooksKickRoute: typeof ApiPublicWebhooksKickRoute
  ApiPublicWebhooksStreamelementsRoute: typeof ApiPublicWebhooksStreamelementsRoute
  ApiPublicWebhooksStreamlabsRoute: typeof ApiPublicWebhooksStreamlabsRoute
  ApiPublicWebhooksTwitchRoute: typeof ApiPublicWebhooksTwitchRoute
  ApiPublicAuthProviderCallbackRoute: typeof ApiPublicAuthProviderCallbackRoute
  ApiPublicAuthProviderStartRoute: typeof ApiPublicAuthProviderStartRoute
  ApiPublicGiveawayTokenLiveRoute: typeof ApiPublicGiveawayTokenLiveRoute
  ApiPublicMediaRequestTokenAdvanceRoute: typeof ApiPublicMediaRequestTokenAdvanceRoute
  ApiPublicMediaRequestTokenLiveRoute: typeof ApiPublicMediaRequestTokenLiveRoute
  ApiPublicMediaRequestTokenStreamRoute: typeof ApiPublicMediaRequestTokenStreamRoute
  ApiPublicModQueueTokenActionRoute: typeof ApiPublicModQueueTokenActionRoute
  ApiPublicModQueueTokenQueueRoute: typeof ApiPublicModQueueTokenQueueRoute
  ApiPublicOverlayPublicIdLiveRoute: typeof ApiPublicOverlayPublicIdLiveRoute
  ApiPublicOverlayPublicIdMetaRoute: typeof ApiPublicOverlayPublicIdMetaRoute
  ApiPublicOverlayPublicIdStreamRoute: typeof ApiPublicOverlayPublicIdStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod-queue': {
      id: '/mod-queue'
      path: '/mod-queue'
      fullPath: '/mod-queue'
      preLoaderRoute: typeof ModQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity-feed': {
      id: '/_authenticated/activity-feed'
      path: '/activity-feed'
      fullPath: '/activity-feed'
      preLoaderRoute: typeof AuthenticatedActivityFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clip-command': {
      id: '/_authenticated/clip-command'
      path: '/clip-command'
      fullPath: '/clip-command'
      preLoaderRoute: typeof AuthenticatedClipCommandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clips': {
      id: '/_authenticated/clips'
      path: '/clips'
      fullPath: '/clips'
      preLoaderRoute: typeof AuthenticatedClipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/giveaway': {
      id: '/_authenticated/giveaway'
      path: '/giveaway'
      fullPath: '/giveaway'
      preLoaderRoute: typeof AuthenticatedGiveawayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-counter': {
      id: '/_authenticated/live-counter'
      path: '/live-counter'
      fullPath: '/live-counter'
      preLoaderRoute: typeof AuthenticatedLiveCounterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media-requests': {
      id: '/_authenticated/media-requests'
      path: '/media-requests'
      fullPath: '/media-requests'
      preLoaderRoute: typeof AuthenticatedMediaRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clip/$id': {
      id: '/clip/$id'
      path: '/clip/$id'
      fullPath: '/clip/$id'
      preLoaderRoute: typeof ClipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/$publicId': {
      id: '/overlay/$publicId'
      path: '/overlay/$publicId'
      fullPath: '/overlay/$publicId'
      preLoaderRoute: typeof OverlayPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/giveaway': {
      id: '/overlay/giveaway'
      path: '/overlay/giveaway'
      fullPath: '/overlay/giveaway'
      preLoaderRoute: typeof OverlayGiveawayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/media-request': {
      id: '/overlay/media-request'
      path: '/overlay/media-request'
      fullPath: '/overlay/media-request'
      preLoaderRoute: typeof OverlayMediaRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/subathon-timer': {
      id: '/overlay/subathon-timer'
      path: '/overlay/subathon-timer'
      fullPath: '/overlay/subathon-timer'
      preLoaderRoute: typeof OverlaySubathonTimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/tiktok-tap-goal': {
      id: '/overlay/tiktok-tap-goal'
      path: '/overlay/tiktok-tap-goal'
      fullPath: '/overlay/tiktok-tap-goal'
      preLoaderRoute: typeof OverlayTiktokTapGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/tiktok-tappers': {
      id: '/overlay/tiktok-tappers'
      path: '/overlay/tiktok-tappers'
      fullPath: '/overlay/tiktok-tappers'
      preLoaderRoute: typeof OverlayTiktokTappersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/widgets/': {
      id: '/_authenticated/widgets/'
      path: '/widgets'
      fullPath: '/widgets/'
      preLoaderRoute: typeof AuthenticatedWidgetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/widgets/$widgetId': {
      id: '/_authenticated/widgets/$widgetId'
      path: '/widgets/$widgetId'
      fullPath: '/widgets/$widgetId'
      preLoaderRoute: typeof AuthenticatedWidgetsWidgetIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subathons/$id/control': {
      id: '/_authenticated/subathons/$id/control'
      path: '/subathons/$id/control'
      fullPath: '/subathons/$id/control'
      preLoaderRoute: typeof AuthenticatedSubathonsIdControlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subathons/$id/overlay': {
      id: '/_authenticated/subathons/$id/overlay'
      path: '/subathons/$id/overlay'
      fullPath: '/subathons/$id/overlay'
      preLoaderRoute: typeof AuthenticatedSubathonsIdOverlayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subathons/$id/rules': {
      id: '/_authenticated/subathons/$id/rules'
      path: '/subathons/$id/rules'
      fullPath: '/subathons/$id/rules'
      preLoaderRoute: typeof AuthenticatedSubathonsIdRulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/widgets/$widgetId/': {
      id: '/_authenticated/widgets/$widgetId/'
      path: '/'
      fullPath: '/widgets/$widgetId/'
      preLoaderRoute: typeof AuthenticatedWidgetsWidgetIdIndexRouteImport
      parentRoute: typeof AuthenticatedWidgetsWidgetIdRoute
    }
    '/_authenticated/widgets/$widgetId/control': {
      id: '/_authenticated/widgets/$widgetId/control'
      path: '/control'
      fullPath: '/widgets/$widgetId/control'
      preLoaderRoute: typeof AuthenticatedWidgetsWidgetIdControlRouteImport
      parentRoute: typeof AuthenticatedWidgetsWidgetIdRoute
    }
    '/_authenticated/widgets/$widgetId/goal': {
      id: '/_authenticated/widgets/$widgetId/goal'
      path: '/goal'
      fullPath: '/widgets/$widgetId/goal'
      preLoaderRoute: typeof AuthenticatedWidgetsWidgetIdGoalRouteImport
      parentRoute: typeof AuthenticatedWidgetsWidgetIdRoute
    }
    '/_authenticated/widgets/$widgetId/rules': {
      id: '/_authenticated/widgets/$widgetId/rules'
      path: '/rules'
      fullPath: '/widgets/$widgetId/rules'
      preLoaderRoute: typeof AuthenticatedWidgetsWidgetIdRulesRouteImport
      parentRoute: typeof AuthenticatedWidgetsWidgetIdRoute
    }
    '/api/auth/callback/tiktok': {
      id: '/api/auth/callback/tiktok'
      path: '/api/auth/callback/tiktok'
      fullPath: '/api/auth/callback/tiktok'
      preLoaderRoute: typeof ApiAuthCallbackTiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clip/$id': {
      id: '/api/public/clip/$id'
      path: '/api/public/clip/$id'
      fullPath: '/api/public/clip/$id'
      preLoaderRoute: typeof ApiPublicClipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/kick': {
      id: '/api/public/webhooks/kick'
      path: '/api/public/webhooks/kick'
      fullPath: '/api/public/webhooks/kick'
      preLoaderRoute: typeof ApiPublicWebhooksKickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/streamelements': {
      id: '/api/public/webhooks/streamelements'
      path: '/api/public/webhooks/streamelements'
      fullPath: '/api/public/webhooks/streamelements'
      preLoaderRoute: typeof ApiPublicWebhooksStreamelementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/streamlabs': {
      id: '/api/public/webhooks/streamlabs'
      path: '/api/public/webhooks/streamlabs'
      fullPath: '/api/public/webhooks/streamlabs'
      preLoaderRoute: typeof ApiPublicWebhooksStreamlabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/twitch': {
      id: '/api/public/webhooks/twitch'
      path: '/api/public/webhooks/twitch'
      fullPath: '/api/public/webhooks/twitch'
      preLoaderRoute: typeof ApiPublicWebhooksTwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/$provider/callback': {
      id: '/api/public/auth/$provider/callback'
      path: '/api/public/auth/$provider/callback'
      fullPath: '/api/public/auth/$provider/callback'
      preLoaderRoute: typeof ApiPublicAuthProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/$provider/start': {
      id: '/api/public/auth/$provider/start'
      path: '/api/public/auth/$provider/start'
      fullPath: '/api/public/auth/$provider/start'
      preLoaderRoute: typeof ApiPublicAuthProviderStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/giveaway/$token/live': {
      id: '/api/public/giveaway/$token/live'
      path: '/api/public/giveaway/$token/live'
      fullPath: '/api/public/giveaway/$token/live'
      preLoaderRoute: typeof ApiPublicGiveawayTokenLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media-request/$token/advance': {
      id: '/api/public/media-request/$token/advance'
      path: '/api/public/media-request/$token/advance'
      fullPath: '/api/public/media-request/$token/advance'
      preLoaderRoute: typeof ApiPublicMediaRequestTokenAdvanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media-request/$token/live': {
      id: '/api/public/media-request/$token/live'
      path: '/api/public/media-request/$token/live'
      fullPath: '/api/public/media-request/$token/live'
      preLoaderRoute: typeof ApiPublicMediaRequestTokenLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media-request/$token/stream': {
      id: '/api/public/media-request/$token/stream'
      path: '/api/public/media-request/$token/stream'
      fullPath: '/api/public/media-request/$token/stream'
      preLoaderRoute: typeof ApiPublicMediaRequestTokenStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mod-queue/$token/action': {
      id: '/api/public/mod-queue/$token/action'
      path: '/api/public/mod-queue/$token/action'
      fullPath: '/api/public/mod-queue/$token/action'
      preLoaderRoute: typeof ApiPublicModQueueTokenActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mod-queue/$token/queue': {
      id: '/api/public/mod-queue/$token/queue'
      path: '/api/public/mod-queue/$token/queue'
      fullPath: '/api/public/mod-queue/$token/queue'
      preLoaderRoute: typeof ApiPublicModQueueTokenQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/overlay/$publicId/live': {
      id: '/api/public/overlay/$publicId/live'
      path: '/api/public/overlay/$publicId/live'
      fullPath: '/api/public/overlay/$publicId/live'
      preLoaderRoute: typeof ApiPublicOverlayPublicIdLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/overlay/$publicId/meta': {
      id: '/api/public/overlay/$publicId/meta'
      path: '/api/public/overlay/$publicId/meta'
      fullPath: '/api/public/overlay/$publicId/meta'
      preLoaderRoute: typeof ApiPublicOverlayPublicIdMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/overlay/$publicId/stream': {
      id: '/api/public/overlay/$publicId/stream'
      path: '/api/public/overlay/$publicId/stream'
      fullPath: '/api/public/overlay/$publicId/stream'
      preLoaderRoute: typeof ApiPublicOverlayPublicIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedWidgetsWidgetIdRouteChildren {
  AuthenticatedWidgetsWidgetIdControlRoute: typeof AuthenticatedWidgetsWidgetIdControlRoute
  AuthenticatedWidgetsWidgetIdGoalRoute: typeof AuthenticatedWidgetsWidgetIdGoalRoute
  AuthenticatedWidgetsWidgetIdRulesRoute: typeof AuthenticatedWidgetsWidgetIdRulesRoute
  AuthenticatedWidgetsWidgetIdIndexRoute: typeof AuthenticatedWidgetsWidgetIdIndexRoute
}

const AuthenticatedWidgetsWidgetIdRouteChildren: AuthenticatedWidgetsWidgetIdRouteChildren =
  {
    AuthenticatedWidgetsWidgetIdControlRoute:
      AuthenticatedWidgetsWidgetIdControlRoute,
    AuthenticatedWidgetsWidgetIdGoalRoute:
      AuthenticatedWidgetsWidgetIdGoalRoute,
    AuthenticatedWidgetsWidgetIdRulesRoute:
      AuthenticatedWidgetsWidgetIdRulesRoute,
    AuthenticatedWidgetsWidgetIdIndexRoute:
      AuthenticatedWidgetsWidgetIdIndexRoute,
  }

const AuthenticatedWidgetsWidgetIdRouteWithChildren =
  AuthenticatedWidgetsWidgetIdRoute._addFileChildren(
    AuthenticatedWidgetsWidgetIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityFeedRoute: typeof AuthenticatedActivityFeedRoute
  AuthenticatedClipCommandRoute: typeof AuthenticatedClipCommandRoute
  AuthenticatedClipsRoute: typeof AuthenticatedClipsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGiveawayRoute: typeof AuthenticatedGiveawayRoute
  AuthenticatedLiveCounterRoute: typeof AuthenticatedLiveCounterRoute
  AuthenticatedMediaRequestsRoute: typeof AuthenticatedMediaRequestsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWidgetsWidgetIdRoute: typeof AuthenticatedWidgetsWidgetIdRouteWithChildren
  AuthenticatedWidgetsIndexRoute: typeof AuthenticatedWidgetsIndexRoute
  AuthenticatedSubathonsIdControlRoute: typeof AuthenticatedSubathonsIdControlRoute
  AuthenticatedSubathonsIdOverlayRoute: typeof AuthenticatedSubathonsIdOverlayRoute
  AuthenticatedSubathonsIdRulesRoute: typeof AuthenticatedSubathonsIdRulesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityFeedRoute: AuthenticatedActivityFeedRoute,
  AuthenticatedClipCommandRoute: AuthenticatedClipCommandRoute,
  AuthenticatedClipsRoute: AuthenticatedClipsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGiveawayRoute: AuthenticatedGiveawayRoute,
  AuthenticatedLiveCounterRoute: AuthenticatedLiveCounterRoute,
  AuthenticatedMediaRequestsRoute: AuthenticatedMediaRequestsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWidgetsWidgetIdRoute:
    AuthenticatedWidgetsWidgetIdRouteWithChildren,
  AuthenticatedWidgetsIndexRoute: AuthenticatedWidgetsIndexRoute,
  AuthenticatedSubathonsIdControlRoute: AuthenticatedSubathonsIdControlRoute,
  AuthenticatedSubathonsIdOverlayRoute: AuthenticatedSubathonsIdOverlayRoute,
  AuthenticatedSubathonsIdRulesRoute: AuthenticatedSubathonsIdRulesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ModQueueRoute: ModQueueRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ClipIdRoute: ClipIdRoute,
  OverlayPublicIdRoute: OverlayPublicIdRoute,
  OverlayGiveawayRoute: OverlayGiveawayRoute,
  OverlayMediaRequestRoute: OverlayMediaRequestRoute,
  OverlaySubathonTimerRoute: OverlaySubathonTimerRoute,
  OverlayTiktokTapGoalRoute: OverlayTiktokTapGoalRoute,
  OverlayTiktokTappersRoute: OverlayTiktokTappersRoute,
  ApiAuthCallbackTiktokRoute: ApiAuthCallbackTiktokRoute,
  ApiPublicClipIdRoute: ApiPublicClipIdRoute,
  ApiPublicWebhooksKickRoute: ApiPublicWebhooksKickRoute,
  ApiPublicWebhooksStreamelementsRoute: ApiPublicWebhooksStreamelementsRoute,
  ApiPublicWebhooksStreamlabsRoute: ApiPublicWebhooksStreamlabsRoute,
  ApiPublicWebhooksTwitchRoute: ApiPublicWebhooksTwitchRoute,
  ApiPublicAuthProviderCallbackRoute: ApiPublicAuthProviderCallbackRoute,
  ApiPublicAuthProviderStartRoute: ApiPublicAuthProviderStartRoute,
  ApiPublicGiveawayTokenLiveRoute: ApiPublicGiveawayTokenLiveRoute,
  ApiPublicMediaRequestTokenAdvanceRoute:
    ApiPublicMediaRequestTokenAdvanceRoute,
  ApiPublicMediaRequestTokenLiveRoute: ApiPublicMediaRequestTokenLiveRoute,
  ApiPublicMediaRequestTokenStreamRoute: ApiPublicMediaRequestTokenStreamRoute,
  ApiPublicModQueueTokenActionRoute: ApiPublicModQueueTokenActionRoute,
  ApiPublicModQueueTokenQueueRoute: ApiPublicModQueueTokenQueueRoute,
  ApiPublicOverlayPublicIdLiveRoute: ApiPublicOverlayPublicIdLiveRoute,
  ApiPublicOverlayPublicIdMetaRoute: ApiPublicOverlayPublicIdMetaRoute,
  ApiPublicOverlayPublicIdStreamRoute: ApiPublicOverlayPublicIdStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
